Selenium Practice Assignment
krishnakTechnocretids/Jan19SeleniumG1 pull request #6
Opened 2019-03-08 16:21 UTC by VishalKTechnocredits

Hello Amarja and Shraddha, 
Please review my code.

2019-03-09 13:17 UTC, AmarjaBTechnocredits reviewed
In Runnable class, 
 import org.openqa.selenium.WebDriver; -> Remove the unused import.
 =================================
1]In Alert Handling class ,Please remove unused comments.
2] You can optimize the lines of code , by writing for all the x-path
driver.findElement(By.xpath(prop.getProperty("firstnameXpath"))).sendKeys(firstName);

this as 
driver.findElement(By.xpath(prop.getProperty("firstnameXpath"))).sendKeys(prop.getProperty("firstname"));

2019-03-09 13:23 UTC, AmarjaBTechnocredits requested changes
All the methods are different assignments and should run independent of each other in Runnable class if I comment the 
1]ah.verifyAlertDemo(); method the other functions fail.Please make it generic or independent of each other
2]When we run the program we are getting below exception
On Registration Page
Alert text is not correct
Exception in thread "main" org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Success!}
  (Session info: chrome=72.0.3626.121)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds: null

Correct the same.

2019-03-09 14:32 UTC, AmarjaBTechnocredits reviewed
Validation is missing for the below error messages

String userNameValidationExpected = "Username length should be greater then 5 characters.";
		String passwordExpectedText = "password is mandatory field.";
		String ReTypePasswordExpectedText = "please reenter password";
		String passwordDontMatchExpectedText = "retype password donot match.";

Please add

2019-03-09 14:36 UTC, AmarjaBTechnocredits approved these changes

2019-03-22 05:46 UTC, KrishnaKTechnocredits approved these changes
From next time onwards please take of formatting and code cleaning, don't comment unexpected code just remove them and write proper comments on every logic.

2019-03-22 05:46 UTC, krishnakTechnocretids commented on seleniumByTechnocredits/src/seleniumPractise/vishal/AlertHandling.java
> +		String expectedText = firstName + " and " + lastName + " and " + company;
Here you can directly write like  String firstName = prop.getProperty("firstname");
No need to create a extra variable.

2019-03-22 05:47 UTC, merged